### ISSUE TITLE
Issue with nativescript-angular 3.1?

### ISSUE THREAD

**Issue by emircm** [PeterStaev/nativescript-masked-text-field#10]
Hello,

I've recently migrated my project to nativescript-angular 3.1. I've observed that angular integration is not working anymore. Here is my MaskedTextField:

<MaskedTextField
              #cellph
              row="4" col="1"
              class="textfield-after-label"
              mask="(00) 00000 0009"
              [(ngModel)]="cellphone"
              keyboardType="number"
              returnKeyType="next"
              (returnPress)="cellphoneReturnPressed()">
</MaskedTextField>

My component does't receive the field value anymore.
Would anybody have any advice?
Thanks in advance.

**Comment by PeterStaev** [comment]
Hey @emircm , I've just tried your mask on the demo project which i updated to TNS 3.1 and nativescript-angular 3.1 and it works fine for me.

**Comment by felipewaku** [comment]
@PeterStaev I am having the same issue, I believe this problem is related to `keyboardType="number"` :/

@emircm As your input is a phone number I think you can use `keyboardType="phone"`, which as I tested worked

**Comment by PeterStaev** [comment]
Hey @felipewaku , I've just tried with `keyboardType="number"` and for me it works for both ios and android when using latest angular and TNS. Can you create a small sample app that reproduces the problem?

**Comment by justmykk** [comment]
I am experiencing the same issue. TNS 3.1.2

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
