### ISSUE TITLE
ngModel doesn't work on both platforms

### ISSUE THREAD

**Issue by alexandruantonica** [PeterStaev/nativescript-masked-text-field#15]
Hi @PeterStaev 

I tried your examples in my app but I realised that the variable I added in `[(ngModel)]` is always `null` or `empty`, depends on init value.

component.html
```
<MaskedTextField class="input-code" [(ngModel)]="code"  keyboardType="phone" mask="0-0-0-0-0" returnKeyType="next" (returnPress)="continue()"></MaskedTextField>
```

`nativescript` : `3.3.1` 
`tns-android` : `3.3.1`
`tns-ios` : `3.3.0`

Let me know if you need more info about my app & test case.

**Comment by akaco** [comment]
Have same issue on `[(ngModel)] `is always null

```
Angular 5.2.1
nativescript : 3.4.1
tns-android : 3.4.1
tns-ios : 3.4.1
```

**Comment by PeterStaev** [comment]
Hey @akaco , I've tried in the `demo-ng` project and I cannot simulate it using the latest version of the plugin. So make sure you are using the latest version of the plugin.

**Comment by akaco** [comment]
Hi this is my setup
in `package.json `

 "nativescript-masked-text-field": "^2.0.1",

in `compnent.ts `
`public smsNumber = '0';`
in Html file
 ```
<MaskedTextField class="input input-border phoneInput" mask="00000000000" [(ngModel)]="smsNumber" keyboardType="phone" row="0"
                                col="1"></MaskedTextField>
```
and I get Null for ngModel smsNumber

**Comment by PeterStaev** [comment]
@akaco I cannot simulate the problem with the `demo-ng` app in the repo. I would suggest you nuke your `node_modules` and `platforms` folders and then try again.

**Comment by mauricioribeiro** [comment]
I'm having the same issue here, but using Vue. Any suggestion?
