### ISSUE TITLE
Mask with placeholders doesn't show in iOS

### ISSUE THREAD

**Issue by alexandruantonica** [PeterStaev/nativescript-masked-text-field#16]
Hi @PeterStaev,

I use your plugin but I found something that bothers me. In Android, the mask shows and it looks exactly like in `mask` property but in iOS, it looks like a blank TextField and when I click on TextField it appears. 

Can you help me, please?

**Comment by PeterStaev** [comment]
Hi @alexandruantonica , 

I cannot simulate this behavior. I've tried with the `demo-ng` app in this repo and both on iOS and Android when the bound value is empty the placeholder characters are visible.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
