### ISSUE TITLE
Add ability to specify the placeholder characters

### ISSUE THREAD

**Issue by PeterStaev** [PeterStaev/nativescript-masked-text-field#2]

**Comment by seveneye** [comment]
any news or workarounds on this?

**Comment by PeterStaev** [comment]
This is now available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
