### ISSUE TITLE
There is some config to make it strip the mask off the data?

### ISSUE THREAD

**Issue by reinaldorauch** [PeterStaev/nativescript-masked-text-field#20]
I want to mask a field that has the format like 999.999.999-99 but i want to get from the text prop the value "cleaned" like 99999999999. There is some configuration that I can make to this? Like the ol' jquery 
 [masked input](https://github.com/digitalBush/jquery.maskedinput)?

**Comment by btaluy** [comment]
For now you can also use .replace(/\D/g, ''); to remove everything from the value except numbers.

**Comment by PeterStaev** [comment]
Currently there is no such functionality, but this can easily be achieved with the suggestion above. Marking this as enhancement but will consider it low priority.

**Comment by reinaldorauch** [comment]
I will try to implement this. Any thoughts ini how to do it?

I think in add an option to the element: stripMask="true" or stripMaskOnOutput="true" to not introduce a BC change. To strip the mask i though in using the very mask to do the job. It may be very straightforward.

**Comment by kefahB** [comment]
Hi, 
It can be cool if we can hide or not the `Underscores` from the MaskedTextField :-)

**Comment by PeterStaev** [comment]
This is now available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
