### ISSUE TITLE
Nativescript Angular: Cant use (focus) on IOS

### ISSUE THREAD

**Issue by btaluy** [PeterStaev/nativescript-masked-text-field#21]
Hey Guys,

I am trying to use the (focus) functionality of textfield on the MaskedTextField component. This works for android but not for IOS. We are still on nativescript 3.4 and maybe this is fixed in the new version of maskedTextField, im not sure. But for us its still broken.

Hope you guys van help us out with this.

Kind regards,
BT

**Comment by PeterStaev** [comment]
Hey @btaluy , I do not understand what are you trying to do and you do not have any sample code, so not much I can do. It is best you create a sample on the playgorund that demonstrates the problem. 

Note that the iOS implementation has a specific implementation that the cursor goes in the beginning of the field when the field is focused:
https://github.com/PeterStaev/nativescript-masked-text-field/blob/8d800f58631a4a408fb40420ca4464bfea4e792b/masked-text-field.ios.ts#L99-L101

**Comment by btaluy** [comment]
I'm trying to use the (focus) event on your plugin, since it extends the textField component it should work. The (blur) event works fine with it on IOS. try to use (focus) on your component in nativescript angular, you will see that the function which is assigned to the focus event does not get triggered.

EDIT: The function you have added to this part will always bring the cursor back to the beginning of the input instead of what im trying to achieve. (when there is focus on the label go further where you were)

If you still need some code I can set up a playground for you, but the code speaks for it self.

**Comment by PeterStaev** [comment]
Hey @btaluy , I think I found the problem and it should be fixed in the new version on npm.
