### ISSUE TITLE
Cannot change mask dynamically in Android

### ISSUE THREAD

**Issue by darkyelox** [PeterStaev/nativescript-masked-text-field#25]
Hello, i'm trying to change the mask of a phone input using this library, the idea is use a component that changes the country, with that country i get the countryCode ('US', 'CO', etc) and use libphonenumber-js for create a phone mask, at this point everything is fine but when i use a directive which is applied to the MaskedTextField for change the mask property against a country the text field behavior is wrong, with random number position, some "(" are changed by numbers when start to typing, the field becomes cyclic (you start to typing and reaching to the end the caret moves to the begining and so on); i tested it in Android, this is my directive code for reference:

```TypeScript
import { Directive, Input, ViewChild, ElementRef } from '@angular/core';
import { Country } from '~/modules/core/vos/country.vo';
import { MaskedTextField } from 'nativescript-masked-text-field/masked-text-field'
import { AsYouType, CountryCode } from 'libphonenumber-js'
import * as phoneNumber from 'libphonenumber-js/examples.mobile.json'

@Directive({
  selector: '[countryPhoneMask]'
})
export class CountryPhoneMaskDirective {

  private _countryPhoneMask: Country

  public maskedTextField: MaskedTextField

  @Input()
  set countryPhoneMask(country: Country) {
    this._countryPhoneMask = country

    if (country) {
      const countryCode = country.countryCode as CountryCode
      const mask = new AsYouType(countryCode).input(phoneNumber[country.countryCode].replace(/[0-9]/g, '9'))
      console.log('NEW PHONE MASK',countryCode, mask)
      this.maskedTextField.mask = mask
    }
  }

  get countryPhoneMask() {
    return this._countryPhoneMask
  }

  constructor(private elRef: ElementRef) {
    this.maskedTextField = elRef.nativeElement
  }

}
```

Then in a template:

``` XML
<MaskedTextField #cellPhoneField="ngModel" id="cell-phone-text" hint="{{'auth.additional-sign-up.cellphone-hint' | L}}"
            [(ngModel)]="user.cellPhone" keyboardType="phone" [countryPhoneMask]="user.country" required></MaskedTextField>
```

How i can change the mask dinamically?, it's possible with this plugin?

**Comment by PeterStaev** [comment]
Hey @darkyelox , currently the plugin does not support changing the mask ad-hoc. This was meant to be set at the start (that's why there is no binding property for the mask as well). 

As a workaround you should be able to use multiple controls with hardcoded masks and `*ngIf` statements to show/hide the correct one for the current country.

**Comment by PeterStaev** [comment]
This is now available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
