### ISSUE TITLE
Quantifier support

### ISSUE THREAD

**Issue by BearOutThere** [PeterStaev/nativescript-masked-text-field#26]
Is there a way to specify quantity of mask characters like '9*' for '0 or more digits'?
I'm trying to specify an email mask.

Thanks.

**Comment by PeterStaev** [comment]
Hey @bearoutthere , this is currently not supported. I guess you will be able to achieve this **when** the plugin adds custom rules support (#1).

**Comment by seveneye** [comment]
+1. This is a very common scenario when you want to mask letters or numbers.
