### ISSUE TITLE
Text underline

### ISSUE THREAD

**Issue by DanielRitvas** [PeterStaev/nativescript-masked-text-field#27]
Is there any way underline of placeholder could be hidden or recoloured?
<img width="309" alt="screenshot 2018-10-31 at 13 07 00" src="https://user-images.githubusercontent.com/13576478/47784321-df91fc80-dd0d-11e8-8606-1aa501f8247d.png">

**Comment by PeterStaev** [comment]
Hey @DanielRitvas , currently there is no such way. You can change the color of the widget, but this will also change the color of the text inside it. 

There is already an issue (#2) to support custom placeholder characters. Once implemented you will be able to define the placeholder as a space, which will basically achieve hiding the placeholder characters.

**Comment by DanielRitvas** [comment]
@PeterStaev thanks for fast response. Any ideas how long it might take to implement custom placeholders? :)

**Comment by PeterStaev** [comment]
Currently I cannot commit to any ETA.
