### ISSUE TITLE
Error Mask with Nativescript 5.0.0

### ISSUE THREAD

**Issue by nericode** [PeterStaev/nativescript-masked-text-field#28]
How are you, thanks for the plugin. When I upgrade to version 5.0.0 the plugin stopped working.

Esenario:

My mask is 99/99 and I write in the specific input but the plugin collects me the following:

Error:

12/22_

Expected

12/22

The error is that I'm adding another script _

**NOTE: In ios not work...**

**Comment by PeterStaev** [comment]
Hey @NeriCodec , since NS 5.0 was just released I did not have the time to test my plugins against it. In general there should not be any difference unless the bump to Android 28 broke something. I'm usually waiting at least couple of weeks so the NS version can be polished before I start using it in production.

**Comment by nericode** [comment]
Thanks @PeterStaev  for your quick response, Android may be right, but the plugin also stops working on iOS, what happens there is that the plugin simply does not apply the mask.

I have returned to version `4.2.0` and I have no problems, I think the only thing that needs to wait is to stabilize version `5.0.0`, thanks.

**Comment by donjuandx** [comment]
Experiencing the same issues on NS 5 after upgrading our app earlier today. No turning back for us on the upgrade so I will try and debug the issue and return with more comments if I find the issue....

**Comment by alexisconsuegra** [comment]
It does not work for me either. I just installed the plugin and I am running tns 5.0. The issue I am having is that the typed characters do not replace nor follow the mask.
<mtf:MaskedTextField id="mobilePhone" text="{{ mobilePhone }}" class="input" keyboardType="phone" mask="000-000-0000" />

**Comment by nickykln** [comment]
+1
@PeterStaev : Do you think you will have the time to fix ?

Thanks in advance.

**Comment by PeterStaev** [comment]
Sadly lately having too much things on my head and I cannot give you any ETA for this 😢

**Comment by nickykln** [comment]
Thanks you @PeterStaev, I can wait a little bit.
Just to let you know, so far, there is no "masked input" plugin working on NS5 :(

**Comment by PeterStaev** [comment]
Hey guys, I pushed a new version on npm that is compatible with TNS 5+. Please update and it should resolve this problem 😉

**Comment by nickykln** [comment]
Hi Peter, 

You are right, it is working again. Thanks a lot. 
This only bug I found is related to hint. 
Previously, The hint text was display and the mask appears on focus. 
Right now, the mask is displayed right away.

Do you need a repo to reproduce ?

Thank you very much, Mister @PeterStaev :)

N

**Comment by PeterStaev** [comment]
@nickykln , the hint is shown ONLY if the bound value is `null` or `undefined`. In any other case the empty mask is shown. It was always working like this so i do not consider this an issue.

**Comment by nickykln** [comment]
Hi @PeterStaev 
Thanks a lot for your quick answer. 
Actually you are right with Ios, but with android I cannot have the hint displayed. 
Find the playground test : 
https://play.nativescript.org/?template=play-ng&id=Iq91kF

You will see that with android, the hint is not displayed. 
What am I doing wrong ?

Thanks again and again.

Nico

**Comment by nericode** [comment]
Thanks @PeterStaev !!!

**Comment by AklsKiu** [comment]
Thank you very much ;) @PeterStaev

**Comment by alexisconsuegra** [comment]
I tried to get the newer version but running tns plugin add nativescript-masked-text-field
but it failed. It says plug in already installed. How can I update it?
________________________________

**Comment by nericode** [comment]
I had not had the opportunity to try the new improvement, but you can do it and apparently the same error persists, do you have any solution?
