### ISSUE TITLE
Installation causes Android failure

### ISSUE THREAD

**Issue by mchallenger88** [PeterStaev/nativescript-masked-text-field#31]
I installed the plugin in my Angular Nativescript app and got the attached errors in Sidekick, and the app would not start. The only way to remove the error was to remove the plugin and delete the Android folder in platforms. Tried a second time with the same result.

![2018-12-22_7-50-05](https://user-images.githubusercontent.com/30409225/50375160-99933f80-05be-11e9-8d40-433566d9a88a.jpg)

**Comment by PeterStaev** [comment]
Hey @mchallenger88 , in the error log I do not see any reference to the plugin itself. So do not think this relates to it. Make sure your developer environment is set up correctly.

**Comment by mchallenger88** [comment]
Thanks for responding.

It's possible it's not the plugin, but installing the plugin creates 
that error. Removing the plugin eliminates the error.

Other plugins works without a problem.

------ Original Message ------

**Comment by mchallenger88** [comment]
Although I did just try to install the moment javascript library, and I 
received a similar error.

Maybe it is something with my environment. My apologies if I spoke too 
soon.

------ Original Message ------

**Comment by mchallenger88** [comment]
Another follow up. It seems the error (at least from the moment install) 
occurs only in Sidekick. I removed the library, deleted platforms, 
reinstalled it and compiled from within VS Code and had no errors.

I'll try installing the plugin and compiling in VS Code a bit later 
since I've moved on from the immediate need.



------ Original Message ------

**Comment by mchallenger88** [comment]
I apologize. I just installed and compiled with VS Code and it works 
great. Thanks for the plugin!

------ Original Message ------

**Comment by mchallenger88** [comment]
Peter-

I am experiencing a couple of problems with the Masked Text Box. First, 
my form values have a trailing underscore "_". For example, if I have a 
telephone number mask, it will look like "(212) 555-5555_" when I 
retrieve the value.

The second thing is odder. When I have a blank field, when pushing a 
couple of keys I have sometimes ended up with the textbox mask 
disappearing and in its place is the word "false". It's happened a 
couple of times, but I just tried to recreate the steps and I couldn't. 
I'm not sure exactly which keys I'm pressing, but I think it is some 
combination of the arrow keys or the backspace.

I'm using the Angular version.

Thanks in advance,
Mark

------ Original Message ------

**Comment by PeterStaev** [comment]
@mchallenger88 , please  do not revive old tasks when the problem is totally different than the original issue. Created #32
