### ISSUE TITLE
Trailing mask character with Angular

### ISSUE THREAD

**Issue by PeterStaev** [PeterStaev/nativescript-masked-text-field#32]
Peter-

I am experiencing a couple of problems with the Masked Text Box. First, 
my form values have a trailing underscore "_". For example, if I have a 
telephone number mask, it will look like `"(212) 555-5555_"` when I 
retrieve the value.

The second thing is odder. When I have a blank field, when pushing a 
couple of keys I have sometimes ended up with the textbox mask 
disappearing and in its place is the word "false". It's happened a 
couple of times, but I just tried to recreate the steps and I couldn't. 
I'm not sure exactly which keys I'm pressing, but I think it is some 
combination of the arrow keys or the backspace.

I'm using the Angular version.

Thanks in advance,
Mark

**Comment by PeterStaev** [comment]
Hey @mchallenger88, on what platform is this happening? And what is your mask exactly? Would be nice if you can provide a playground link simulating the mask problem. 

For the second items, if you cannot recreate it yourself, then sadly I cannot provide any guidance/help. If you can recreate it please again provide a playground link together with detailed steps how to reproduce.

**Comment by mchallenger88** [comment]
The platform is Android.

The telephone mask is "(999) 999-9999" but it it also happens with my social security mask "999-99-9999".  I will try to recreate on the playground and send a link. I'll update you when I figure out how to recreate the weird false thing.
