### ISSUE TITLE
Hint does not show on android when value is null

### ISSUE THREAD

**Issue by PeterStaev** [PeterStaev/nativescript-masked-text-field#33]
Hi @PeterStaev 
Thanks a lot for your quick answer. 
Actually you are right with Ios, but with android I cannot have the hint displayed. 
Find the playground test : 
https://play.nativescript.org/?template=play-ng&id=Iq91kF

You will see that with android, the hint is not displayed. 
What am I doing wrong ?

Thanks again and again.

Nico

_Originally posted by @nickykln in https://github.com/PeterStaev/nativescript-masked-text-field/issues/28#issuecomment-445805158_

**Comment by PeterStaev** [comment]
Hey @nickykln, I can confirm that this is an issue with both core and angular versions on android. I will see what I can do about it 😉

**Comment by nickykln** [comment]
Thanks so much @PeterStaev 
It is working great.

Do you plan a new release soon ? 

Thanks again. 

Nicolas

**Comment by PeterStaev** [comment]
@nickykln , the fix is already available in npm.
