### ISSUE TITLE
It doesn't work with keyboardType "number"

### ISSUE THREAD

**Issue by Selminha** [PeterStaev/nativescript-masked-text-field#34]
I'm trying to use MaskedTextField with keyboardType "number" and mask "999.999.999-99", but it doesn't work.
It works if I use other mask like this "(999) 999999" or keyboardType "phone"

**Comment by PeterStaev** [comment]
Hey @Selminha , please provide more details like what platform are you testing this on, what {N} version are you using, is it an angular based or not. 

Best option will be to provide a reproducible example on the NativeScript Playground.

**Comment by Selminha** [comment]
Hi, I'm testing on android 8.0, {N} version 5.3.1 and it isn't angular based.
Sorry I'm not using playground so I don't have any example to provide right now. 
I will try to prepare an example on playground and I put it here as soon as I have it.

**Comment by PeterStaev** [comment]
Here is a link to a plyground that demonstrates the problem: https://play.nativescript.org/?template=play-tsc&id=3TrL4w&v=2

Happens on Android only.

**Comment by PeterStaev** [comment]
Hey @Selminha , this should now be resolved with the new version just pushed on npm (4.0.2)
