### ISSUE TITLE
Text Masking support in NativeScript Angular 

### ISSUE THREAD

**Issue by M-kothakapu** [PeterStaev/nativescript-masked-text-field#40]
Hi, I'm looking to create an SSN masking for text field using asterisk * (or) hash #. For example, I want to mask my ssn text field as  ***-**-***  or  ###-##-####.

I haven't found any sample in the documentation https://github.com/PeterStaev/nativescript-masked-text-field . Could you please provide me this add on feature to generate a text masking for ssn using *  or #.

I have posted this issue in NativeScript group too. Please refer to the following URL.
https://github.com/NativeScript/nativescript-angular/issues/1877

**Comment by PeterStaev** [comment]
Hey @M-kothakapu , what you want is out of the scope of this plugin. This plugin is used to enter pre-formatted text, not replace the characters with some symbol. But you can mask the text using a regex replace with the symbol you want.
