### ISSUE TITLE
The raw value displays a trailing _

### ISSUE THREAD

**Issue by dpdragnev** [PeterStaev/nativescript-masked-text-field#44]
Hello Peter,

After switching to NS 6.0 I started experiencing an issue with the plugin.  When the user enters the information in the text box, the value still contains an extra _ (underscore) character.

Here is a playground link to demonstrate the issue:

https://play.nativescript.org/?template=play-tsc&id=Sv3mjI

Thank you for your help.

**Comment by PeterStaev** [comment]
Hey @dpdragnev , what platform are you testing? Just tested on iOS (dont have an android device right now) and I dont see the problem.

**Comment by dpdragnev** [comment]
Sorry, forgot to mention that.  I am using Android.  iOS is fine.

**Comment by PeterStaev** [comment]
Hey @dpdragnev , I was able to simulate and fix the issue. The fix is now available in the latest version available at [ProPlugins](https://npm.proplugins.org).

**Comment by dpdragnev** [comment]
Thank you @PeterStaev

**Comment by dpdragnev** [comment]
@PeterStaev I am trying to install it, but I am getting:

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@proplugins%2fnativescript-masked-text-field - Not found
npm ERR! 404
npm ERR! 404  '@proplugins/nativescript-masked-text-field@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

I also tried installing it via Sidekick, but I cannot even see the plugin there.

Any suggestion?

**Comment by PeterStaev** [comment]
@dpdragnev . [ProPlugins](https://proplugins.org/) is a subscription based service. Once you subscribe, you will gain access to the above mentioned private NPM registry.

**Comment by dpdragnev** [comment]
Got you.  Thanks.

**Comment by Nevaan** [comment]
Okay, so in this case - there are no plans to fix this in version available on github? Or are you going to upload it with delay?

**Comment by PeterStaev** [comment]
@Nevaan , currently I have no plans to upload changes to the public repo/npm. But things might change 😃

**Comment by Nevaan** [comment]
Okay, thanks a lot for quick response :) so - maybe you could add some notice that plugin is no longer under development (at least, here)? I believe your plugin is one of few plugins providing input masking feature available on NativeScript marketplace, unfortunately not working properly with Android :(

**Comment by PeterStaev** [comment]
@Nevaan , this is the first statement in the readme with bold text:
>This repo only supports NativeScript pre-6.0. The latest version of the plugin supporting NS 6+ is availble as part of ProPlugins.

**Comment by Nevaan** [comment]
oops - you are right. I did not try to use it for NS <6 and somehow skipped this in your statement :)
