### ISSUE TITLE
Strange behavior in Android

### ISSUE THREAD

**Issue by lb0ss** [PeterStaev/nativescript-masked-text-field#48]
Hi,

After updating my project to NativeScript 6 and Angular 8, the plugin behaves in an unexpected way on Android with the setup of mask="99/99" in the MaskedTextField element to represent expiration date in MM/YY format. When I entered a date, an additional underscore is added to the value of the input field, causing the input to have an invalid value. When a "maxLength" property is provided, the masked input will stop accepting input altogether after the first digit is entered. However, the exact setup works fine on iOS. 

Please refer to the screenshot below for the symptom described above:
<img width="396" alt="Screen Shot 2020-04-02 at 22 39 45" src="https://user-images.githubusercontent.com/13360346/78328184-68305000-7533-11ea-819d-5f69752aebe3.png">
<img width="339" alt="Screen Shot 2020-04-02 at 22 39 56" src="https://user-images.githubusercontent.com/13360346/78328196-70888b00-7533-11ea-98ea-c063619b4511.png">
<img width="404" alt="Screen Shot 2020-04-02 at 22 46 01" src="https://user-images.githubusercontent.com/13360346/78328328-c2c9ac00-7533-11ea-8858-ced11faf9dd6.png">
<img width="408" alt="Screen Shot 2020-04-02 at 22 46 06" src="https://user-images.githubusercontent.com/13360346/78328330-c52c0600-7533-11ea-8a03-3fdf95f2bf9b.png">

Since the input mask feature depends on the plugin, any help is highly appreciated. Thanks in advance.

**Comment by PeterStaev** [comment]
Hey @lb0ss , there have been many breaking changes with NS6. I've just tested you scneario in the ProPlugins version of the plugin and it works fine there. Also it has many new features - like custom place holder characters and stripping mask characters from the value. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.

**Comment by lb0ss** [comment]
Hi Peter, 
Thank you for your response.  It seems that the Pro Plugin site only lists monthly subscription fee. Is there an annual subscription option?

**Comment by PeterStaev** [comment]
Hi @lb0ss , it has both. Once you create an account and go to the subscribe page this is what you will see:
![image](https://user-images.githubusercontent.com/9464097/78577461-c6f91080-7836-11ea-92d7-173386659b77.png)

**Comment by lb0ss** [comment]
Hi Peter, 

Thank you. I subscribed yesterday and upgraded the plugin to the latest version. The bug has been resolved. 

However, it seems that the support for NativeScript Theme 2.0 classes have not yet been added. MaskedTextField elements with "nt-input" or "input -border" classes will not produce the styling as in a built in TextField element. Would there be any estimated time as to when the supported will be added?

**Comment by PeterStaev** [comment]
Not sure what do you mean. If the CSS is there I dont see why the plugin would be different. AFAIK there are no additional changes need for plugins in order to support the theme. 

Please create an issue and provide an example in the ProPlugins repo (https://git.proplugins.org)

**Comment by lb0ss** [comment]
Hi Peter, 
I tried creating an account and log in directly with my Github account. But it wouldn't allow me too. That said, I hope it's OK to post the example of the issue here.

As you can see in the screenshots, when "nt-input" is applied to a regular NativeScript TextField, its styling is reflected properly in the input field. However, the MaskedTextField with "nt-input" class doesn't reflect the styling either on day mode or night mode. I've also tried a few more input related classes but no luck.

<img width="370" alt="Screen Shot 2020-04-08 at 20 46 53" src="https://user-images.githubusercontent.com/13360346/78855943-22afcf00-79da-11ea-9704-6c7c8e6333c9.png">
<img width="365" alt="Screen Shot 2020-04-08 at 20 46 58" src="https://user-images.githubusercontent.com/13360346/78855946-24799280-79da-11ea-95a5-77c61c4d9021.png">
<img width="524" alt="Screen Shot 2020-04-08 at 20 47 38" src="https://user-images.githubusercontent.com/13360346/78855994-4d018c80-79da-11ea-8253-7b458ad94f00.png">
<img width="521" alt="Screen Shot 2020-04-08 at 20 48 14" src="https://user-images.githubusercontent.com/13360346/78856000-4ecb5000-79da-11ea-8db4-ed33933bad23.png">

**Comment by PeterStaev** [comment]
I think you should use the same account as you use for the ProPlugins NPM registry. If it doesnt work, please ping Nathanael Anderson on Slack or email at nathan[at]proplugins[dot]org

For the issue I will review when i get a chance. It could be that NS restricted this class only to `TextField`.
