### ISSUE TITLE
The cursor is positioned at the end of the field

### ISSUE THREAD

**Issue by Yamilquery** [PeterStaev/nativescript-masked-text-field#5]
When I run demo-ng, the cursor is positioned at the end of the field.

So I can not write anything

![simulator screen shot 09 05 2017 21 35 31](https://cloud.githubusercontent.com/assets/6020065/25880860/7835d74e-34ff-11e7-8eb3-d695c7278f70.png)

**Comment by PeterStaev** [comment]
Hey @Yamilquery , this is the default behavior of UITextFields in iOS. When the field gets focus it automatically goes to the end of the line. I was thinking to automatically go at the start, but I'm not sure if changing the default behavior is a good thing. I will leave this open for now and will see if there will be more push to change the default behavior.

**Comment by newapx** [comment]
+1

**Comment by KBorecki** [comment]
Hey @PeterStaev . i think the placing cursor on end of the input value is default behavior for filled input. in fact at the start the textField isnt filled, contain only mask. Soo in this case default and natural behavior will be placing cursor on the end the real value :)

**Comment by emircm** [comment]
Even thou this is the default behavior on iOS, from a user perspective the cursor should be in the beginning, so he can type and see the characters in the right place.

**Comment by mrkorsar** [comment]
It would be great if the cursor will be in the beginning of the field. I need this feature. Please!
