### ISSUE TITLE
No MaskedTextFieldModule found in Angular

### ISSUE THREAD

**Issue by johnnyzen** [PeterStaev/nativescript-masked-text-field#6]
Hi there

Is angular/ts fully working, as cannot seem to find MaskedTextFieldModule when imported:

import { MaskedTextFieldModule } from "nativescript-masked-text-field/angular";

"node_modules/nativescript-masked-text-field/masked-text-field"' has no exported member 'MaskedTextFieldModule'."

Any ideas?

**Comment by PeterStaev** [comment]
Hey @johnnyzen , the demo-ng project in this repo is a fully working one. You need to build the plugin from the repo or change in package.json to pull from NPM and not from path.
